import type { Metadata } from 'next'
import Providers from '@/app/providers'
import { GlobalStyle } from '@/styles/global'
import Container from '@/components/global/Container'
import Header from '@/components/global/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <GlobalStyle />
          <Container>
            <Header />
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  )
}
